[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - 4627 - LOGS_CAPTURED - Started capturing logs in process (pid: 4627).
[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - 4627 - internal_generate_cluster_visualizations - STEP_START - Started execution of step "internal_generate_cluster_visualizations".
[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - internal_generate_cluster_visualizations - Loading file from: storage/internal_assign_clusters using PickledObjectFilesystemIOManager...
[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - 4627 - internal_generate_cluster_visualizations - LOADED_INPUT - Loaded input "internal_assign_clusters" using input manager "io_manager", from output "result" of step "internal_assign_clusters"
[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - internal_generate_cluster_visualizations - Loading file from: storage/internal_train_clustering_models using PickledObjectFilesystemIOManager...
[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - 4627 - internal_generate_cluster_visualizations - LOADED_INPUT - Loaded input "internal_train_clustering_models" using input manager "io_manager", from output "result" of step "internal_train_clustering_models"
[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - 4627 - internal_generate_cluster_visualizations - STEP_INPUT - Got input "internal_assign_clusters" of type "Dict[String,DataFrame]". (Type check passed).
[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - 4627 - internal_generate_cluster_visualizations - STEP_INPUT - Got input "internal_train_clustering_models" of type "Dict[String,Any]". (Type check passed).
[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - 4627 - internal_generate_cluster_visualizations - STEP_OUTPUT - Yielded output "result" of type "Dict[String,[String]]". (Type check passed).
Exception while writing logger call to event log: (sqlite3.DatabaseError) file is not a database
[SQL: INSERT INTO event_logs (run_id, event, dagster_event_type, timestamp, step_key, asset_key, partition) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('17209dab-d6d1-44b5-8358-fa949323170c', '{"__class__": "EventLogEntry", "dagster_event": null, "error_info": null, "level": 10, "message": "", "pipeline_name": "internal_ml_job", "run_id": " ... (105 characters truncated) ... ": 1744755551.9351249, "user_message": "Writing file at: storage/internal_generate_cluster_visualizations using PickledObjectFilesystemIOManager..."}', None, '2025-04-15 22:19:11.935125', 'internal_generate_cluster_visualizations', None, None)]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
Exception while writing logger call to event log: (sqlite3.DatabaseError) file is not a database
[SQL: INSERT INTO event_logs (run_id, event, dagster_event_type, timestamp, step_key, asset_key, partition) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('17209dab-d6d1-44b5-8358-fa949323170c', '{"__class__": "EventLogEntry", "dagster_event": {"__class__": "DagsterEvent", "event_specific_data": {"__class__": "StepFailureData", "error": {"__cl ... (12246 characters truncated) ... _cluster_visualizations", "timestamp": 1744755551.974306, "user_message": "Execution of step \\"internal_generate_cluster_visualizations\\" failed."}', 'STEP_FAILURE', '2025-04-15 22:19:11.974306', 'internal_generate_cluster_visualizations', None, None)]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
